### ISSUE TITLE
Error starting client (beta) (have I done something wrong maybe?)

### ISSUE THREAD

**Issue by yorrd** [Nefelim4ag/League-Of-Legends#10]
Hi, thanks for the archlinux package, been waiting for something like this :)

This is in lol_client.log whenever I try "leagueoflegends client"

> wine: cannot find L"\\\\?\\unix\\home\\usrname\\whatever\\path\\im\\in\\atm\\."

Reproduce: Install from AUR, run "leagueoflegends client". Am I missing something?

**Comment by Nefelim4ag** [comment]
@yorrd, did you install beta client?

**Comment by yorrd** [comment]
Stupid me. Thanks for the explanation. Maybe you could add a hint in the --help output?

Everything working fine now, as expected =)

**Comment by Nefelim4ag** [comment]
Like this?
https://github.com/Nefelim4ag/League-Of-Legends/commit/6adeeddf0985cc9b08f054093bdbdf58d8b64a73
