### ISSUE TITLE
Probably missing adobe AIR

### ISSUE THREAD

**Issue by samosaara** [Nefelim4ag/League-Of-Legends#11]
The installer simply instantly crashed after the logo because it were missing adobe air. (I know because it started working after I've `leagueoflegends winetricks adobeair`) shouldn't it be part of required stuff alongside core fonts and ETC.?

**Comment by Nefelim4ag** [comment]
Installer? Do you mean launcher?
Can you attach some logs?
---
It's strange, i already use this to deploy LoL on several machines and on all, it's work without adobe air %)

Can you describe you environment? (I'll try reproduce and find why adobe air are needed)

**Comment by samosaara** [comment]
http://pastebin.com/uv6cRsj2
That's all the info i could think of. Hit me up if you need any other. I don't think i still have the logs of the 'lack of adobe air' crashes, but i do remember they being all vague... Just messages like not possible to initialize etc. And the crashes were to bug splash instantly as soon as the logo finished loading

**Comment by Nefelim4ag** [comment]
@samosaara, oh, all the same to the my machine =\
So, i get launcher working without Adobe Air error, on win32 and win64 wine prefixes, only that i do, is just restart launcher several times:
```
$ leagueoflegends wineserver -k
$ leagueoflegends launcher
```

For working launcher RADS download ~155mb of data (and not download more until you accept licence),  so if you want test, just make backup of lol, and try:
```
mv ~/.local/share/leagueoflegends ~/.local/share/leagueoflegends.backup
```

**Comment by samosaara** [comment]
The current solution is to restart until it works? Isn't it better to add a 5mb download and make it work out of the box?

**Comment by Nefelim4ag** [comment]
@samosaara, it's will crash several time independent of adobe air, if i install it, or if not.

So, not better =\
