### ISSUE TITLE
Beta Client crash after update

### ISSUE THREAD

**Issue by yorrd** [Nefelim4ag/League-Of-Legends#12]
Heyo again, after the patch today, the beta launcher just instantly results in a bugsplat upon starting. This is in the console output:

`
INFO: LoL Client UNIX path: /home/user/.local/share/leagueoflegends/WINE.win32/dosdevices/x:/RADS/projects/league_client/releases/0.0.0.36/deploy/LeagueClient.exe`

`INFO: LoL Client WINE path: X:\RADS\projects\league_client\releases\0.0.0.36\deploy\LeagueClient.exe
`

which makes me think you're maybe hardcoding 0.0.0.36 instead of using the latest?

Also, there has been wine Version 1.9.24-2, but I hardly think it's because of that.

**Comment by Nefelim4ag** [comment]
Oh, fucking riots who which don't clean up dirs after path =_=''
I just use find, for search LeagueClient.exe as i expect path can be changed, but i don't expect i have a several files

Thanks for suggestion, i will try fix it soon.

**Comment by yorrd** [comment]
Ok if you're searching, I'll try just removing the old folder manually. Will report back.

**Comment by yorrd** [comment]
@Nefelim4ag lul that fixed it. It should do if you just remove the old directories :)

**Comment by Nefelim4ag** [comment]
@yorrd, Fixed problem for me
https://github.com/Nefelim4ag/League-Of-Legends/commit/197b5cf3d95708ffca319d9ddb2dddff3540469e
