### ISSUE TITLE
winetricks bloat dependencies by default

### ISSUE THREAD

**Issue by Limdel** [Nefelim4ag/League-Of-Legends#13]
Not a big issue, especially considering that it is possible to edit config, but still, the only things that are needed to be installed via winetricks to run league are vcrun2013 and d3dx9.

**Comment by Nefelim4ag** [comment]
@Limdel, did you try create fresh installation with only this two deps?
I try it and this don't work.
Latest ArchLinux and Wine 1.9.24 win32

**Comment by Limdel** [comment]
yes I did. both on manjaro and arch linux. always worked for me.
however, right now I have issues launching new client after patch, but I sear it always worked and I started using your scripts only 2 days ago.

**Comment by Nefelim4ag** [comment]
@Limdel, Fix problem after 6.24: https://github.com/Nefelim4ag/League-Of-Legends/issues/12

**Comment by Limdel** [comment]
ye I saw it. I have different problem now. updater shows 0.0 MB / 0.0 MB and nothing happens, which is common bug even on windows it seems.
and yes, I'm using wine staging. it requires less libs? if yes, then I'm sorry.

**Comment by ardarandir** [comment]
what should we be using if not wine-staging?
ist winehq-staging better?
