### ISSUE TITLE
Can't login in Wine 2.0

### ISSUE THREAD

**Issue by Carl-Marx** [Nefelim4ag/League-Of-Legends#19]
In version 2.0 of Wine is impossible to log in. The message "Logging in..." never disappears, I've waited for hours and nothing. Please fix it ;-;

**Comment by Carl-Marx** [comment]
`fixme:imm:ImmReleaseContext (0x40060, 0x6925138): stub
fixme:powermgnt:PowerCreateRequest (0x33f140): stub
fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 30000
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:powermgnt:PowerCreateRequest (0x33f140): stub
fixme:powermgnt:PowerCreateRequest (0x33f140): stub
fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 5000
fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 5000
fixme:powermgnt:PowerCreateRequest (0x33f140): stub`

**Comment by Nefelim4ag** [comment]
@Carl-Marx, ArchLinux Wine 2.0rc4 64bit prefix
Launcher and new client working without any issues.

**Comment by Carl-Marx** [comment]
Well.. Not for me.
I have to use downgrader, none of the clients are logging in. :/

**Comment by ardarandir** [comment]
did you search the web for this issue? sound like a very commong connection issue, see here:
http://forums.euw.leagueoflegends.com/board/showthread.php?t=2058453

**Comment by Carl-Marx** [comment]
Yes, I've tried to disable TCP Timestamps, but still doesn't log in. :/
The problem is wine 2.0 (tried wine-staging, same result).
I'm using downgrader to return to 1.9.9, that still works.

**Comment by Carl-Marx** [comment]
Apparently, it's working with this new Wine version :/
