### ISSUE TITLE
Launcher don't open and i can only close with system monitor

### ISSUE THREAD

**Issue by JotaPe** [Nefelim4ag/League-Of-Legends#21]
Hello i use Manjaro Gnome 16.10 with the kernel on 4.8

The launcher opens but don't do nothing and the wine says to reinstall and i reinstalled it but nothing, i can only close with the System Monitor.

Sorry for bad english.

And one question the you are using the StandAlone launcher or other launcher ?

And i'm using the latest driver of nvidia for linux and a GTX 970

**Comment by Carl-Marx** [comment]
Hello!

Take a look in this post: https://wiki.archlinux.org/index.php/League_of_Legends#Install_the_dependencies

Have you tried to use "leagueoflegends wineserver -k" instead of closing it with Sistem Monitor?

**Comment by ardarandir** [comment]
please post logs and screenshots of error messages so we can narrow down possible issues. thanks.
