### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by Erwyn** [Nefelim4ag/League-Of-Legends#22]
Hello there,

I have a new problem. The launcher works great, no issue there. But when I start a game I get a black screen for like 20-30 seconds and then bugsplat.

I will try to provide you with logs later on. Wine version is 2.0 Staging.

**Comment by Erwyn** [comment]
okay my bad I was missing some drivers...

**Comment by Nefari0uss** [comment]
@Erwyn Please post what drivers you were missing as this info could potentially help someone else.

**Comment by Erwyn** [comment]
Sure, I am on fedora, installing steam brought me these which made it work:

libva-intel-driver
mesa-dri-drivers
