### ISSUE TITLE
Black screen when I enter a game

### ISSUE THREAD

**Issue by InvokeWebRequest** [Nefelim4ag/League-Of-Legends#28]
Hey!

I can log in perfectly fine, and I can go through champ select. But when loading starts I see no loading screen, only a black screen. Also when the game has loaded, i can see the chat, but everything else is black. What could this issue be. I can post any logs / info. Installed using yaourt from AUR
![screenshot_20170419_225416](https://cloud.githubusercontent.com/assets/27040764/25212973/5039d684-2553-11e7-9db5-79f83563b5cb.png)
![screenshot_20170419_225426](https://cloud.githubusercontent.com/assets/27040764/25212974/504f798a-2553-11e7-8c11-1553c3e4cd6a.png)

**Comment by Rodsevich** [comment]
@InvokeWebRequest  How did you fix this?
