### ISSUE TITLE
Shellcheck conformity

### ISSUE THREAD

**Issue by ChuckDaniels87** [Nefelim4ag/League-Of-Legends#3]
You should check the bash scripts with [Shellcheck](http://www.shellcheck.net/). The package is in the community repo. It shows some errors and warnings in your scripts.

Nice idea, btw. :+1:

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, thanks, i already used it for long time.
This tool are too aggressive sometimes. ;)

**Comment by ChuckDaniels87** [comment]
I agree it is a bit aggressive. Nevertheless I think it is a good idea at least to double quote some lines where appears `$PREFIX` and `$LOL_INSTALL_PATH`. Spaces there can break things.

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, did i miss something https://github.com/Nefelim4ag/League-Of-Legends/commit/0d031c369042fc1bf98fa4d4a3eb3d9a009b1e70 ?

**Comment by ChuckDaniels87** [comment]
In that file is fine now but some warning in the `install.sh` script are still present.

**Comment by Nefelim4ag** [comment]
Oh, thanks, i fixed all shell scripts
