### ISSUE TITLE
Multiuser system

### ISSUE THREAD

**Issue by ChuckDaniels87** [Nefelim4ag/League-Of-Legends#4]
Correct me if I'm wrong, but I think this method won't work in multi-user system since it the game is installed in a user wine directory inside its home.

Maybe using a standard directory like `/opt` this could be fixed.

I've also noticed that `$PREFIX` is a variable in [install.sh](https://github.com/Nefelim4ag/League-Of-Legends/blob/master/install.sh) but the paths are hardcoded in some checks in [leagueoflegends](https://github.com/Nefelim4ag/League-Of-Legends/blob/master/leagueoflegends) script. [This one for example](https://github.com/Nefelim4ag/League-Of-Legends/blob/master/leagueoflegends#L33-L38).

**Comment by Nefelim4ag** [comment]
Oh,
/* I hate prefix support, i use it for packaging */

For multiuser as i think, it's can be easy fixed by something like:
```
# mkdir /opt/leagueoflegends
# chmod 0775 /opt/leagueoflegends
# chown nobody:users /opt/leagueoflegends
# echo 'LOL_INSTALL_PATH="/opt/leagueoflegends" ' >> /etc/leagueoflegends.conf 
```
I don't test it, but i create LOL_INSTALL_PATH for this case and in theory it must do the trick.

Thanks.

**Comment by ChuckDaniels87** [comment]
Another problem would be several users trying to run League of Legends at the same time, but it is a improbable case and Wine does not support that.

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, by default each user have own copy of LoL and Wine Prefix
So it's must cover any multiuser cases. (It's behaviour like Linux Steam)
But it's produce wasted space, so fix for wasted space below.

Wasted storage can be freed with two ways:
- By deduplication - XFS/Btrfs deduplication - Prefered solution as it will not break something in any cases.
- By remove most duplicated data - game itself as i suggest abowe with shared game dir
---
Do we try solve some real case or just think how to work with it?

**Comment by ChuckDaniels87** [comment]
I misunderstood the wrapper workflow. I think it is fine for multi-user but as you noted it will create duplicated data. I don't think that 6GB of duplicated data would be a problem in a modern system. I really doubt that more than 2 or 3 users would install LoL in a real use case. 

Using XFS/Btrfs may be excessive and probably a restrictive solution. It is fine as it is right now. 

Nice job btw!

**Comment by Nefelim4ag** [comment]
Thanks =)
