### ISSUE TITLE
Install script on AUR package

### ISSUE THREAD

**Issue by ChuckDaniels87** [Nefelim4ag/League-Of-Legends#5]
I think that most part of install script should be in the `PKGBUILD`. That is the reason why AUR packages exists. You could keep the rest of the script in GitHub but there are some functions to better handle packages that you should take a look at.

Desktop file can be also pregenerated and installed as the rest of the files. That is the common way of do it.

_Edit: Maybe, you plan to support other distros different from Archlinux, don't you?_

**Comment by Nefelim4ag** [comment]
Yes, i just try create general distro solution for League Of Legends, i just don't have time to port my https://github.com/Nefelim4ag/Ananicy/blob/master/package.sh script for this project

**Comment by ChuckDaniels87** [comment]
Nice, I did not know that this was a multidistro wrapper. 

However, I think desktop file should be pregenerated, it is the same in all distros.

**Comment by Nefelim4ag** [comment]
1. Desktop file - fixed: https://github.com/Nefelim4ag/League-Of-Legends/commit/7e3bad0721131d62ad35815c0c216cda753a5792
2. Replace yaourt with auto local build: https://github.com/Nefelim4ag/League-Of-Legends/commit/199bd8514ac05b3125e748cc69307af46906d448
