### ISSUE TITLE
Fail to reinstall

### ISSUE THREAD

**Issue by ChuckDaniels87** [Nefelim4ag/League-Of-Legends#6]
If you cancel the installation of the game, it won't try to reinstall anymore. It would be nice if the script let you choose to reinstall in case of not finding the launcher.

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, i've rewrite script, at now it's use another installation method.

So it must be not a problem.

**Comment by ChuckDaniels87** [comment]
Are thise files taken from the publisher? Are you sure you can distribute them without the infringement of any license?

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, yes this files before has been auto deployed by [fat installer](http://l3cdn.riotgames.com/Installer/SingleFileInstall/LeagueOfLegendsBaseEUW.exe)
I don't find any information about this in Riot License.
So i think rules are general for any binary blob of freeware: "Not try to Resell"

**Comment by ChuckDaniels87** [comment]
Being freeware doesn't imply that you can redistribute the binary files. If you don't find anything, I would try to contact someway the company and ask them about this to avoid problems in the future.

**Comment by ChuckDaniels87** [comment]
As I thought, [the license](http://na.leagueoflegends.com/legal/termsofuse#limited-license) is restrictive:

> 3.1. What can I do with the Riot Services? (You can enjoy the Riot Services for your own, personal, non-commercial use.)
> 
> We grant you a limited, non-exclusive, non-transferable, revocable license to use and enjoy the Riot Services for your individual, non-commercial, entertainment purposes only and expressly conditioned upon your compliance with the terms of this Agreement. Unless otherwise expressly authorized by us in a signed writing, you may not sell, copy, exchange, loan, reverse engineer, decompile, derive source code from, translate, lease, grant a security interest in, transfer, publish, assign or otherwise distribute any of the Riot Services or any of Riot Games’ intellectual property, including any computer code associated therewith.

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, oh, do i understand correctly, what i can't redistribute binary files?
/* Sounds stupid, because then i can't copy game files to another machine, to my friend's PC & etc */

**Comment by ChuckDaniels87** [comment]
Because it is a limited non-commercial individual license. You need to accept this individually and it is non-transferable. I think that a similar case would be buying DVD Movie and upload it to YouTube.

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87,
But user accept this license then client installed =\
And i don't think that DVD Movie is a good comparison, because in this case i pay for "See movie".
In case with launcher it's free, i don't pay for this and Riot allow to free download and use it.
By script logic i get similiar data, either in case when i download installer and install game, or by just install files to target place.
---
Oh, i will try do request in Riot support with link to this issue.

**Comment by ChuckDaniels87** [comment]
Having no cost does not imply anything. The launcher is free in the sense of no-cost/gratis not in sense of freedom. There is open source software that it is not free and you cannot distribute it without explicit permission. 

Those binaries are owned by Riot and you cannot distribute them without permission. It is pretty clear in the license.

If you want to learn more about this:
* [Freeware](https://en.wikipedia.org/wiki/Freeware)
* [Freeware and Free Software](http://opensource.stackexchange.com/questions/1375/what-is-the-relation-and-or-difference-between-freeware-and-free-software)
* [Open Source and Free Software](http://askubuntu.com/questions/78958/is-there-a-difference-between-free-software-and-open-source-software)

**Comment by Nefelim4ag** [comment]
Oh, i create official request.
https://support.riotgames.com/hc/en-us/requests/24131704

Request message:
```
Many guys play in LoL on Linux machine.

At now we don't have official support, i understand this and it's okay. 
So community made many ways to get LoL running on linux. 
No one are generic, and no one work every time when LoL get update. 
So i try to create general proposed LoL/Wine installer for LoL, with support to all distros. 
https://github.com/Nefelim4ag/League-Of-Legends

It must simplify things, just to simplify life for LoL linux gamers. 
Also it's allow to made general solution for people with community support & fixes/updates. 
--- 
So, for install game, we need a official client installer, but installer work a very bad on linux. 
https://riotgamespatcher-a.akamaihd.net/ShellInstaller/EUNE/LeagueofLegends_EUNE_Installer_2016_05_13.exe

It's big, it's work bad in wine, it's hangs. 
You don't support linux, so you don't need to fix that. 
--- 
So many scripts use old installer like: http://l3cdn.riotgames.com/Installer/SingleFileInstall/LeagueOfLegendsBaseEUW.exe

It's work good, and i use it for some time, but it's big (30Mb) and because it's not native binary i can't check if it's works correctly in code. 
--- 
So i try to use unpacked/installed data from this installator, it's only 1.5Mb and it's easy to install and use. 
https://github.com/Nefelim4ag/League-Of-Legends/tree/master/Launcher

Just copy directory and run. it's work pretty good and simple.

But i have a licensing question, was i breaks some law by this? 
--- 
Issue on github: https://github.com/Nefelim4ag/League-Of-Legends/issues/6

If i understand correctly, by your licence i can't do this. 
But in this case i also breaks the laws if i just copy installed client (just to avoid redownload it) to my friends.

Can you provide some feed back about this?

Thanks.
```

So let's wait official comment about this, thanks for your contribution.

 ---
P.S. I'm not only one who do things like this:
http://fidblog.ru/league-of-legends/
http://boards.ru.leagueoflegends.com/en/c/guides-ru/WsfskHch-league-of-legends-linux-
And I just ignore torrents with wineprefix for LoL.

**Comment by Nefelim4ag** [comment]
So, update.
You can read issue thread on the community support.

It's funny but no one answer to my question, I think that they do not care, so as i write in the thread, that i believe that they give me permission for this action :), and i think that they will not do any protest.

Thanks.

**Comment by ChuckDaniels87** [comment]
I cannot access to the request site. Would you mind to copy the answer here?

**Comment by Nefelim4ag** [comment]
@ChuckDaniels87, np
```
REQUEST #24131704
CAN I COPY INSTALLED LAUNCHER TO ANOTHER MACHINE, IT'S RESTRICTED BY RIOT LICENCE?
Avatar
NEFELIM4AG Wednesday at 13:53
Many guys play in LoL on Linux machine.

At now we don't have official support, i understand this and it's okay. 
So community made many ways to get LoL running on linux. 
No one are generic, and no one work every time when LoL get update. 
So i try to create general proposed LoL/Wine installer for LoL, with support to all distros. 
https://github.com/Nefelim4ag/League-Of-Legends

It must simplify things, just to simplify life for LoL linux gamers. 
Also it's allow to made general solution for people with community support & fixes/updates. 
--- 
So, for install game, we need a official client installer, but installer work a very bad on linux. 
https://riotgamespatcher-a.akamaihd.net/ShellInstaller/EUNE/LeagueofLegends_EUNE_Installer_2016_05_13.exe

It's big, it's work bad in wine, it's hangs. 
You don't support linux, so you don't need to fix that. 
--- 
So many scripts use old installer like: http://l3cdn.riotgames.com/Installer/SingleFileInstall/LeagueOfLegendsBaseEUW.exe

It's work good, and i use it for some time, but it's big (30Mb) and because it's not native binary i can't check if it's works correctly in code. 
--- 
So i try to use unpacked/installed data from this installator, it's only 1.5Mb and it's easy to install and use. 
https://github.com/Nefelim4ag/League-Of-Legends/tree/master/Launcher

Just copy directory and run. it's work pretty good and simple.

But i have a licensing question, was i breaks some law by this? 
--- 
Issue on github: https://github.com/Nefelim4ag/League-Of-Legends/issues/6

If i understand correctly, by your licence i can't do this. 
But in this case i also breaks the laws if i just copy installed client (just to avoid redownload it) to my friends.

Can you provide some feed back about this?

Thanks.
```
```
Avatar
NEMONIKHD Wednesday at 15:34
Hello Nefelim4ag,

NemonikHD here, from League of Legends Player Support, thank you for contacting us.

Unfortunately, League of Legends is not currently supported on Linux and I'm afraid we don’t currently have any plans to create a Linux specific client.

Many of our Linux users have had success playing through WINE. You can find out more about WINE at https://www.winehq.org/. If WINE isn't for you, you can also consider PlayOnLinux, you can find more details at https://www.playonlinux.com/en/.

If you need help along the way both WINE and PlayOnLinux both offer a Wiki and Forums to reach out to other members of their community.

I am sorry that I will be unable to assist you directly with this process, as we currently only support our official Windows and Mac clients.

I hope this helps, and please let us know if you have any other issues that we can work with directly!

Regards,

✪NemonikHD✪

Riot Player Support Specialist
```
```
Avatar
NEFELIM4AG Wednesday at 15:41
This is automatic answer? I think automatic. 
More, i say what i know, what you don't support linux. 
I don't ack about Linux client.

I asked about your rights for yours binaries and about your licenses.
```
```
Avatar
NEMONIKHD Friday at 14:43
Greetings,

We recently announced the open beta of the official Riot Games API. Open beta means that we’re looking to see how players use the tool and what they think of it, so expect some changes before a full release. Check here if you need help getting started:

https://developer.riotgames.com/docs/getting-started

If you want to talk to other players, ask questions of budding developers or just contribute to the community, we’ve set up a forum here:

https://developer.riotgames.com/discussion/community-discussion

Don’t hesitate to let me know if you have any other questions!

✪NemonikHD✪

Riot Player Support Specialist
```
```
Avatar
NEFELIM4AG Friday at 15:38
Ok, thanks, so then. 
Thus, I believe that you give permission for this action.

I will write, if I will have more questions :)
```
```
Avatar
NEMONIKHD Friday at 16:05
Sure, happy to help. ;)

✪NemonikHD✪

Riot Player Support Specialist
```

**Comment by ChuckDaniels87** [comment]
Nice, keep the log just in case.
