### ISSUE TITLE
Use /opt instead of /var

### ISSUE THREAD

**Issue by ChuckDaniels87** [Nefelim4ag/League-Of-Legends#7]
I think that `/opt/leagueoflegends` would be a more appropriate path to place the installer. The `/var` directory it is supposed to store variable data like logs, databases, etc. The `/opt` is used to store individual vendor app and programs that does not follow the standards.

**Comment by Nefelim4ag** [comment]
np, https://github.com/Nefelim4ag/League-Of-Legends/commit/5466186da38c12732b24224b99fc4a17cc7a3452
