### ISSUE TITLE
it gives me bugsplat during installation

### ISSUE THREAD

**Issue by jianu81** [Nefelim4ag/League-Of-Legends#9]
it crashes and gives me bugsplay during  "step 2/2 applying patches" which is also way slower than on pc(i mean it takes an hour most on pc,on linux it takes like 4-5 hours but it crashes)

**Comment by Nefelim4ag** [comment]
It's not a script or installation issue.
I try only guaranty what you got a working wine prefix, launcher and wine prefix.

But, can you add a additional info, wine version, distro, logs?

**Comment by jianu81** [comment]
distro-xubuntu 16.10
wine version-latest staging wine
Sorry but no logs.
Additional info-it took a really long time to apply patches,at least 4 hours

**Comment by Nefelim4ag** [comment]
You can launch it from console:
```
leagueoflegends launcher
```
and see that happens in the logs
```
leagueoflegends tail
```
---
As i have a template of U1604, i try to reproduce you issue.
First thing what i noticed under ubuntu...:
Fisrt thing what i can ask, are you sure that are you using latest staging?
If you use PPA, wine-staging will not export to the default PATH, so you will use the default system version i.e. 1.6.*

above command (to run launcher) will print current binary wine version.

**Comment by Nefelim4ag** [comment]
It's a funny, but i fix problem by:
```
$ leagueoflegends regen_wine_prefix
```
Nope, i can't explain it, but it's works on my test VM.
